### ISSUE TITLE
Camera Sensor Setting is Wrong

### ISSUE THREAD

**Issue by Bob-cheng** [cf206cd/carla_nuscenes#4]
Nuscene says that the exposure time of its camera is 20ms: "Auto exposure with exposure time limited to the maximum of 20 ms"

In your camera sensor definition, the 'shutter_speed' is set to 20 (1.0/s), which means the exposure time is 50ms.

So, you should set the 'shutter_speed' attribute to 50 (1.0/s) at least, which corresponds to 20ms.

**Comment by cf206cd** [comment]
Thank you for your comment！ I just misunderstand the parameter.
